title: "Home"
description: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

custom_css:
  - /assets/css/custom.css

# Theme options for above include
# default – Base/standard look
# air – Calm, light blue tones
# aqua – Water-like blues
# contrast – Bold contrast
# dark – Dark background
# dirt – Earthy tones
# mint – Fresh green accents
# neon – Bright highlights
# plum – Purple palette
# sunrise – Warm oranges



search: false

markdown: kramdown
permalink: pretty

atom_feed:
  hide: true

footer:
  text: "© 2026 My Name or Custom Text"

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: "sidebar"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
